version: "3.9"

services:
  main-service:
    image: iraavas/main-service
    container_name: spring-boot-app
    restart: always
    ports:
      - "${MAIN_SERVICE_PORT}:8081"
    networks:
      - app-network
    mem_limit: ${APP_MEM_LIMIT}
    cpus: ${APP_CPU_LIMIT}
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_SHOW_SQL: ${SHOW_SQL}
      SPRING_FLYWAY_ENABLED: true
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: true
      SERVER_PORT: ${MAIN_SERVICE_PORT}
      TOMCAT_THREADS: ${TOMCAT_THREADS}

      # --- Поддержка Observability ---
      STATISTICS_OBSERVABILITY: true
      OBSERVABILITY_INTERVALS: 10,30,60
      SERVICE_STATISTIC_OBSERVABILITY_DELAY: 5000

  additional-service:
    image: iraavas/additional-service
    container_name: additional-service
    restart: always
    depends_on:
      - main-service
    ports:
      - "${ADDITIONAL_SERVICE_PORT}:8082"
    networks:
      - app-network
    mem_limit: ${APP_MEM_LIMIT}
    cpus: ${APP_CPU_LIMIT}
    environment:
      MAIN_SERVICE_HOST: ${MAIN_SERVICE_HOST}
      MAIN_SERVICE_PORT: ${MAIN_SERVICE_PORT}
      SERVER_PORT: ${ADDITIONAL_SERVICE_PORT}
      TOMCAT_THREADS: ${TOMCAT_THREADS}

      # --- Поддержка Observability (если нужно следить за клиентами) ---
      STATISTICS_OBSERVABILITY: true
      OBSERVABILITY_INTERVALS: 10,30,60
      SERVICE_STATISTIC_OBSERVABILITY_DELAY: 5000

networks:
  app-network:
    driver: bridge
